RUN cd /tmp \
 && git clone --recurse-submodules -b v5.2.0-stable --depth 1 --shallow-submodules https://github.com/wolfssl/wolfssl \
 && cd wolfssl \
 && ./autogen.sh \
 && ./configure --enable-dtls --enable-debug --enable-certgen --enable-tls13 CFLAGS="-DHAVE_SECRET_CALLBACK" --enable-opensslextra \
 && make && make install \
 && cd / && rm -rf /tmp/wolfssl
 