# syntax = edrevo/dockerfile-plus

FROM ubuntu:22.04

INCLUDE+ Dockerfile.common
INCLUDE+ Dockerfile.common.tls

WORKDIR /app
COPY build/librasta_dtls.so build/rasta_grpc_bridge_dtls ./

ENTRYPOINT ["/app/rasta_grpc_bridge_dtls"]
